@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(unregisteredUser, "Незарегистрированный пользователь", "Отсутствуют личные данные в системе")
Person(client, "Клиент", "Пользователь, зарегистрированный в системе, способный оформлять запись на онлайн-консультацию")
Person(expert, "Эксперт", "Пользователь, зарегистрированный в системе как специалист в определенной сфере, способный проводить онлайн-консультации")
Person(administrator, "Администратор", "Управление учетными записями, решение жалоб на экспертов/клиентов/отзывы")

System(system, "Сервис онлайн-консультаций", "Платформа, позволяющая клиентам получать квалифицированные консультации от экспертов в реальном времени через видео, аудио или текстовый чат")
System_Ext(bankingSystem, "Банковская система", "Списание денежных средств клиента")

unregisteredUser --> system: Регистрируется или авторизовывается в системе в качестве клиента / эксперта
client --> system: Клиент выбирает эксперта, оформляет запись на консультацию и производит оплату
expert ---> system: Проводит консультацию
administrator --> system: Решает жалобы на экспертов/клиентов/отзывы, проверяет специализацию эксперта

system --> bankingSystem: Списывает денежные средства клиента

SHOW_LEGEND()
@enduml
