@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(unregisteredUser, "Незарегистрированный пользователь", "Отсутствуют личные данные в системе")
Person(client, "Клиент", "Пользователь, зарегистрированный в системе, способный совершать заказы")
Person(driver, "Водитель", "Пользователь, зарегистрированнный в системе вместе с автомобилем, способный выполнять заказы")
Person(administrator, "Администратор", "Управление учетными записями, формирование отчетов, решение жалоб")
Person(systemAdministrator, "Системный администратор", "Поддержание работы информационной системы, безопасности данных")

System(system, "Система заказа такси", "Выбор наиболее подходящего водителя для клиента")
System_Ext(navigationSystem, "Навигационная система", "Предоставление необходимых геоданных")
System_Ext(bankingSystem, "Банковская система", "Списание денежных средств клиента")
System_Ext(taxiBrokerSystem, "Таксопарк", "Посредничество в работе с водителями")

unregisteredUser --> system: Регистрируется в системе в качестве клиента либо водителя
client --> system: Выбирает маршрут вместе с другими доступными параметрами поездки и заказывает такси
driver ---> system: Выполняет выбранный заказ
administrator --> system: Решает спорные ситуации, проверяет водителей
systemAdministrator --> system: Следит за целостностью системы и безопасностью данных в ней

system --> navigationSystem: Строит маршрут и просчитывает его время/оптимальность
system --> bankingSystem: Списывает денежные средства клиента
system --> taxiBrokerSystem: Переводит заработанные деньги, решить вопросы, связанные с трудоустройством

SHOW_LEGEND()
@enduml
