@startuml
start
:Клиент выбрал параметры заказа (см. Диаграмму процесса 2) и делает заказ такси;
:Система такси создает заказ;
if (Найдены доступные автомобили такси?) then (Нашли доступные машины)
  :Сервис такси уведомляет доступных водителей;
  :Сервис такси получает ответы от доступных водителей;
  if (Водитель принимает заказ?) then (Да)
    :Водитель принимает заказ;
    :Сервис выбирает маршрут;
    :Водитель едет к месту подачи;
    :Водитель прибывает к месту подачи;
    while (Клиент отсутствует на месте подачи?) is (Да)
      :Прибавить минуту ко времени ожидания;
      if (Время ожидание в минутах превысило бесплатный лимит?) then (Да)
        :Запустить платное ожидание;
        :Оповестить клиента о начале платного ожидания;
      endif;
      if (Запущено платное ожидание?) then (Да)
        :Прибавить к стоимости заказа фиксированную сумму ожидания в минуту;
      endif;
    endwhile (Клиент на месте);
    :Клиент садится в машину;
    :Водитель начинает поездку;
    :Водитель везет клиента к месту назначения;
    if (Водитель отклонился от изначального маршрута?) then (Да)
      :Система перестраивает маршрут;
    endif;
    :Водитель завершает поездку;
    if (Водитель завершил поездку раньше?) then (Да)
      :Пересчитать стоимость поездки;
    endif;
    if (У клиента достаточно средств) then (Да)
      :Клиент производит оплату;
    else (Нет)
      :Сервис запоминает долг клиента;
      :Сервис блокирует возможность заказа следующих поездок;
    endif;
  else (Нет)
    :Водитель не принимает заказ;
    :Сервис такси просит попробовать совершить заказ позднее; 
    :Сервис такси отменяет заказ;
  endif
else (Нет)
  :Сервис такси просит попробовать совершить заказ позднее;
  :Сервис такси отменяет заказ;
endif
:Заказ считается завершенным;
stop
@enduml

