@startuml
|Клиент|
start
:Выбрать параметры заказа;
:Оформить заказ;
|Сервис такси|
:Создать заказ;
if (Найдены доступные автомобили такси?) then (Да)
    :Выбрать маршрут подачи;
    :Уведомить доступных водителей на линии;
  |Водитель|
  :Получить уведомление о доступном заказе;
  if (Водитель принимает заказ?) then (Да)
      :В пути к месту подачи;
      :Прибыть к месту подачи;
    |Сервис такси|
    while (Клиент на месте подачи?) is (Нет)
      :Прибавить минуту ко времени ожидания;
      if (Время ожидание в минутах превысило бесплатный лимит?) then (Да)
        :Запустить платное ожидание;
        :Оповестить клиента о начале платного ожидания;
      endif;
      if (Запущено платное ожидание?) then (Да)
        :Прибавить к стоимости заказа фиксированную сумму ожидания в минуту;
      endif;
    endwhile (Да);
    |Клиент|
    :Сесть в машину;
    |Водитель|
    :Начать поездку;
    :Везти клиента к месту назначения;
    if (Водитель отклонился от изначального маршрута?) then (Да)
    |Сервис такси|
      :Перестроить маршрут;
    endif;
    |Водитель|
    if (Клиент указал промежуточную точку остановки?) then (Да)
      :Добраться до промежуточной точки остановки;
      :Ожидать клиента в течение 5 минут;
      if (Клиент просит подождать) then (Да)
        |Сервис такси|
        :Запустить платное ожидание клиента;
        :Уведомить клиента о начале платного ожидания;
        :Пересчитать стоимость поездки;
      endif;
      if (Клиент отсутствует больше 15 минут?) then (Да)
        :Завершить заказ;
      else (Нет)
        |Водитель|
        :Продолжить поездку;
      endif;
    endif;
    :Добраться до конечной точки маршрута;
    |Клиент|
    :Выйти из машины;
    :Получить уведомление о завершении заказа;
    :Получить уведомление с просьбой оценить поездку;
    :Получить уведомление с предложением оставить чаевые;
    if (Клиент желает оценить водителя?) then (Да)
      :Поставить оценку водителю и/или написать краткий отзыв;
    endif;
    if (Клиент желает оставить чаевые?) then (Да)
      :Добавить к стоимости заказа указанную клиентом сумму чаевые;
    endif;
    |Водитель|
    :Завершить поездку;
    if (Водитель завершил поездку раньше?) then (Да)
    |Сервис такси|
      :Пересчитать стоимость поездки;
    endif;
    if (У клиента достаточно средств для оплаты?) then (Да)
      :Произвести оплату со счета клиента;
    else (Нет)
      :Запомнить долг клиента;
      :Заблокировать возможность заказа следующих поездок;
    endif;
  endif
else (Нет)
  |Сервис такси|
  :Попросить попробовать совершить заказ позднее;
  :Отменить заказ;
endif
stop
@enduml